package com.example.drivingschoolapp;

import androidx.room.Entity;
import androidx.room.PrimaryKey;

// This class represents the Booking entity for the Room database
@Entity(tableName = "booking_table")
public class Booking {
    // Primary key for the Booking entity, auto-generated by Room
    @PrimaryKey(autoGenerate = true)
    private int id;

    // Name of the person making the booking
    private String name;

    // Date of the booking
    private String date;

    // Name of the instructor assigned to the booking
    private String instructor;

    // Default constructor required by Room
    public Booking() {
    }

    // Constructor to create a new Booking with specified details
    public Booking(String name, String date, String instructor) {
        this.name = name;
        this.date = date;
        this.instructor = instructor;
    }

    // Getter for the booking ID
    public int getId() {
        return id;
    }

    // Setter for the booking ID
    public void setId(int id) {
        this.id = id;
    }

    // Getter for the name of the person making the booking
    public String getName() {
        return name;
    }

    // Setter for the name of the person making the booking
    public void setName(String name) {
        this.name = name;
    }

    // Getter for the date of the booking
    public String getDate() {
        return date;
    }

    // Setter for the date of the booking
    public void setDate(String date) {
        this.date = date;
    }

    // Getter for the name of the assigned instructor
    public String getInstructor() {
        return instructor;
    }

    // Setter for the name of the assigned instructor
    public void setInstructor(String instructor) {
        this.instructor = instructor;
    }
}
